import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  newuserpopup: {
    borderRadius: 10,
    width: '90%',
    height: 'auto',
    maxHeight: 500,
    backgroundColor: 'white',
    position: 'absolute',
    top: '20%',
    alignSelf: 'center',
  },
  popupscreentitle: {
    height: 30,
    flexDirection: 'row',
    borderColor: 'lightgrey',
    borderBottomWidth: 1,
    paddingLeft: 15,
  },
  title: {
    justifyContent: 'center',
  },
  titletext: {
    color: 'black',
    fontSize: 18,
  },
  crossicon: {
    width: '10%',
    justifyContent: 'center',
    marginLeft: 188,
  },
  label: {
    color: 'black',
    alignSelf: 'flex-start',
    marginBottom: 10,
    fontSize: 15,
  },
  inputView: {
    flexDirection: 'row',
    width: '100%',
    borderWidth: 1,
    borderColor: '#1e90ff',
    borderRadius: 5,
    height: 40,
  },
  name: {
    width: '100%',
    alignItems: 'center',
    marginTop: '6%',
    marginBottom: 35,
    paddingHorizontal: 15,
  },
  emailinvite: {
    height: 40,
    width: '100%',
    alignSelf: 'center',
    flexDirection: 'row',
    paddingHorizontal: 15,
  },
  showviews: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    width: '30%',
  },
  showviewsbutton: {
    width: '100%',
    backgroundColor: 'lightgrey',
    borderRadius: 5,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  invitecontainer: {
    width: 78,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  invitebutton: {
    width: '95%',
    backgroundColor: '#1e90ff',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  showviewspopup: {
    backgroundColor: 'white',
    width: '28%',
    height: 70,
    position: 'absolute',
    top: 40,
    left: 175,
    borderRadius: 5,
    borderWidth: 1,
    zIndex: 1,
  },
  viewonly: {
    width: '100%',
    height: 35,
    borderBottomWidth: 1,
    paddingLeft: 5,
  },
  canedit: {width: 100, height: 35, paddingLeft: 5},
  userinfo: {
    height: 50,
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  canceladd: {
    height: 50,
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 10,
  },
  cancelbutton: {
    backgroundColor: 'grey',
    marginLeft: '15%',
    height: 40,
    width: 90,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addbutton: {
    marginLeft: '15%',
    backgroundColor: '#1e90ff',
    height: 40,
    width: 90,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
